# frozen_string_literal: true

class TabLabelDecorator < SimpleDelegator
  # If the label used for the govuk_tabs component starts with a number
  # the links for switching tabs do not work
  # This overrides paramterize to prefix the string with "_" in these cases
  # The parameterize call is made by the component for the href of the tab
  # not the displayed value.
  # e.g. the label "2021-2022" will be displayed correctly but the href
  #      generated by the tab component will be "#_2021-2022"
  def parameterize(**args)
    if string =~ /^\d+/
      "_#{string.parameterize(**args)}"
    else
      super(**args)
    end
  end

private

  def string
    __getobj__
  end
end
