description: "A list of NPQ applications"
type: object
required:
  - data
properties:
  data:
    type: array
    items:
      $ref: "#/components/schemas/NPQApplication"
    example:
      - id: db3a7848-7308-4879-942a-c4a70ced400a
        type: npq_application
        attributes:
          course_identifier: "npq-leading-teaching-development"
          email: "isabelle.macdonald2@some-school.example.com"
          email_validated: true
          employer_name: null
          employment_role: null
          full_name: "Isabelle MacDonald"
          funding_choice: null
          headteacher_status: null
          ineligible_for_funding_reason: null
          participant_id: "53847955-7cfg-41eb-a322-96c50adc742b"
          private_childcare_provider_urn: null
          teacher_reference_number: "0743795"
          teacher_reference_number_validated: true
          school_urn: "123456"
          school_ukprn: "12345678"
          status: "pending"
          works_in_school: true
          created_at: "2022-07-06T10:47:24Z"
          updated_at: "2022-11-24T17:09:37Z"
          cohort: "2022"
          eligible_for_funding: true
          funded_place: true
          targeted_delivery_funding_eligibility: false
          teacher_catchment: true
          teacher_catchment_iso_country_code: "GBR"
          teacher_catchment_country: "United Kingdom of Great Britain and Northern Ireland"
          itt_provider: null
          lead_mentor: false
