description: "A list of NPQ applications"
type: object
required:
  - data
properties:
  data:
    type: array
    items:
      $ref: "#/components/schemas/NpqApplication"
    example:
      - id: db3a7848-7308-4879-942a-c4a70ced400a
        type: participant
        attributes:
          id: 7a8fef46-3c43-42c0-b3d5-1ba5904ba562
          participant_id: 7a8fef46-3c43-42c0-b3d5-1ba5904ba562
          full_name: "Isabelle MacDonald"
          email: "isabelle.macdonald2@some-school.example.com"
          email_validated: true
          teacher_reference_number: "1234567"
          teacher_reference_number_validated: true
          school_urn: "106286"
          headteacher_status: "no"
          eligible_for_funding: true
          funding_choice: "trust"
          course_identifier: npq-leading-teaching
