---
openapi: 3.0.1
info:
  version: 3.0.0
  title: "Lead provider API - 3.0.0 (Draft)"
  contact:
    name: DfE
    email: continuing-professional-development@digital.education.gov.uk
  description: "The lead provider API for DfE's manage teacher CPD service. You cannot make calls to this version in any environment. We are sharing as a spec only now - your feedback is welcome"
servers:
  - url: https://ecf-sandbox.london.cloudapps.digital
    description: "Sandbox"
  - url: /
    description: "Current environment"
  - url: https://manage-training-for-early-career-teachers.education.gov.uk
    description: "Production"

paths:
components:
  securitySchemes:
    bearerAuth:
      bearerFormat: string
      type: http
      scheme: bearer
  schemas:
    ParticipantDeclarationResponse:
      anyOf:
        - $ref: "#/components/schemas/ECFParticipantDeclarationResponse"
        - $ref: "#/components/schemas/NPQParticipantDeclarationResponse"
      discriminator:
        propertyName: type
security:
  - "bearerAuth": []
