---
openapi: 3.0.1
info:
  version: 3.0.0
  title: "Lead provider API - 3.0.0"
  contact:
    name: DfE
    email: continuing-professional-development@digital.education.gov.uk
  description: "The lead provider API for DfE's manage teacher CPD service."
servers:
  - url: https://sb.manage-training-for-early-career-teachers.education.gov.uk
    description: "Sandbox"
  - url: /
    description: "Current environment"
  - url: https://manage-training-for-early-career-teachers.education.gov.uk
    description: "Production"

paths:
components:
  securitySchemes:
    bearerAuth:
      bearerFormat: string
      type: http
      scheme: bearer
  schemas:
    ParticipantDeclarationResponse:
      $ref: "#/components/schemas/ECFParticipantDeclarationResponse"
      discriminator:
        propertyName: type
security:
  - "bearerAuth": []
