inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - deployed_development
    - staging
