inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'db/seeds/cip_*.rb'
    - 'db/data/**/*.csv'

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  Include:
    - "db/new_seeds"

Layout/EndOfLine:
  EnforcedStyle: lf

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/MixinUsage:
  Exclude:
    - 'db/legacy_seeds/test_data.rb'

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - review
    - sandbox
    - staging
    - test
    - performance

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/Output:
  Exclude:
    - "app/services/importers/*"
    - "app/services/finance/extract_report.rb"

Lint/MissingSuper:
  Enabled: false

Rails/SaveBang:
  Exclude:
    - "app/services/migrators/*"

Style/RedundantFetchBlock:
  Exclude:
    - 'app/middlewares/api_request_middleware.rb'
