plugin_gems: ['scss_lint-govuk']

linters:
  PlaceholderInExtend:
    exclude:
      - "app/webpacker/styles/components/statement_selector.scss"
  BangFormat:
    exclude:
      - "app/webpacker/styles/components/statement_selector.scss"
