groups:
  - name: Request-rates
    rules:
      - alert: RequestsFailuresElevated
        # Condition for alerting
        expr: (sum(rate(requests{app="ecf-staging", status_range=~"0xx|5xx"}[5m]))) / (sum(rate(requests{app="ecf-staging"}[5m])) ) > 0.1
        # Annotation - additional informational labels to store more information
        annotations:
          summary: High rate of failing requests
          description: "ecf-staging: The proportion of failed HTTP requests in the past 5 min is above 10% (current value: {{ humanizePercentage $value }})"
        # Labels - additional labels to be attached to the alert
        labels:
          environment: staging
          severity: medium

  - name: CPU-usage
    rules:
      - alert: AppCPUHigh
        expr: avg by ( app ) (cpu{app="ecf-staging"}) > 60
        for: 5m
        annotations:
          summary: App CPU usage high
          description: "App CPU usage at least 60% for more than 5 minutes (current value: {{ $value }})"
        labels:
          environment: staging
          severity: medium
      - alert: WorkerCPUHigh
        expr: avg by ( app ) (cpu{app=~"ecf-staging-.*worker"}) > 75
        for: 10m
        annotations:
          summary: Worker CPU usage high
          description: "ecf-staging: Worker CPU usage at least 75% for more than 10 minutes (current value: {{ $value }})"
        labels:
          environment: staging
          severity: medium

  - name: Disk-utilisation
    rules:
      - alert: DiskUtilisationHigh
        expr: avg by ( app ) ( disk_utilization{ app=~"ecf-staging" }) > 60
        for: 5m
        annotations:
          summary: Disk Utilization High
          description: "ecf-staging: Disk utilization at least 60% for more than 5 minutes (current value: {{ $value }})"
        labels:
          environment: staging
          severity: medium

  - name: Memory-utilisation
    rules:
      - alert: AppMemoryUtilizationHigh
        expr: avg by ( app ) (memory_utilization{app="ecf-staging"}) > 60
        for: 5m
        annotations:
          summary: Memory Utilization High
          description: "ecf-staging: Memory utilization at least 60% for more than 5 minutes (current value: {{ $value }})"
        labels:
          environment: staging
          severity: medium
      - alert: WorkerMemoryUtilizationHigh
        expr: avg by ( app ) (memory_utilization{app=~"ecf-staging-.*worker"}) > 80
        for: 5m
        annotations:
          summary: Memory Utilization High
          description: "ecf-staging: Memory utilization at least 80% for more than 5 minutes (current value: {{ $value }})"
        labels:
          environment: staging
          severity: medium

  - name: Crashed-apps
    rules:
      - alert: AppsCrashed
        expr: rate(crash{app="ecf-staging"}[1m])*60 > 1
        annotations:
          summary: Crashed Apps non-zero
          description: "ecf-staging: At least 1 crashed app (current value: {{ $value }})"
        labels:
          environment: staging
          severity: medium
      - alert: AppsWorkerCrashed
        expr: rate(crash{app=~"ecf-staging-.*worker"}[1m])*60 > 1
        annotations:
          summary: Crashed Apps non-zero
          description: "ecf-staging-worker: At least 1 crashed app (current value: {{ $value }})"
        labels:
          environment: staging
          severity: medium
