---
RACK_ENV: production
RAILS_ENV: production
NODE_ENV: production
RAILS_LOG_TO_STDOUT: true
RAILS_MAX_THREADS: 5
RAILS_SERVE_STATIC_FILES: true
SERVICE_TYPE: web
DATABASE_URL: postgres://postgres@localhost:5432
DOMAIN: manage-training-for-early-career-teachers.education.gov.uk
GOVUK_WEBSITE_ROOT: manage-training-for-early-career-teachers.education.gov.uk
GOVUK_APP_DOMAIN: manage-training-for-early-career-teachers.education.gov.uk
