AZURE_SUBSCRIPTION=s189-teacher-services-cloud-production
AZURE_RESOURCE_PREFIX=s189p01
DNS_ZONE=cpdecf
RESOURCE_GROUP_NAME=${AZURE_RESOURCE_PREFIX}-${DNS_ZONE}domains-rg
KEYVAULT_NAME=${AZURE_RESOURCE_PREFIX}-${DNS_ZONE}domains-kv
STORAGE_ACCOUNT_NAME=${AZURE_RESOURCE_PREFIX}${DNS_ZONE}domainstf
DOMAINS_ID=cpd_ecf
