description: "A list of participants in the Comma Separated Value (CSV) format"
type: string
required:
  - data
properties:
  data:
    type: array
    items:
      $ref: "#/components/schemas/NPQApplicationCsvRow"
example: |
  id,type,participant_id,full_name,email,email_validated,email_validated,teacher_reference_number,teacher_reference_number_validated,school_urn,headteacher_status,eligible_for_funding,funded_place,funding_choice,course_identifier,status,created_at,updated_at
  db3a7848-7308-4879-942a-c4a70ced400a,npq-application,7a8fef46-3c43-42c0-b3d5-1ba5904ba562,Isabelle MacDonald,isabelle.macdonald2@some-school.example.com,true,1234567,true,106286,no,true,true,trust,npq-leading-teaching,pending,2021-05-31T02:21:32.000Z,2021-05-31T02:22:32.000Z

