description: "The NPQ Application acceptance request attributes"
type: object
required:
  - type
  - data
properties:
  type:
    description: "The data type"
    type: string
    example: "npq-application-accept"
  data:
    $ref: "#/components/schemas/NPQApplicationAcceptAttributesRequest"
