name: Deploy environment to AKS
description: Deploys an application environment to AKS

inputs:
  environment:
    description: The name of the environment
    required: true
  docker-image:
    description: The Docker image to deploy
    required: true
  azure-client-id:
    description: Azure Client ID for authentication
    required: true
  azure-tenant-id:
    description: Azure Tenant ID for authentication
    required: true
  azure-subscription-id:
    description: Azure Subscription ID for authentication
    required: true
  pull-request-number:
    description: The pull request number which triggered this deploy. If set, this will automatically seed the database.
    required: false
  smoke-test-credentials-required:
    description: Whether to run the smoke test with support credentials
    required: false
    default: "true"
  current-commit-sha:
    description: The commit sha for the current commit
    required: true
  statuscake-api-token:
    description: The Statuscake token
    required: false

outputs:
  url:
    description: The base URL for the deployed environment
    value: ${{ steps.apply-terraform.outputs.url }}

runs:
  using: composite

  steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.4
        terraform_wrapper: false

    - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-client-id: ${{ inputs.azure-client-id }}
        azure-tenant-id: ${{ inputs.azure-tenant-id }}
        azure-subscription-id: ${{ inputs.azure-subscription-id }}

    - uses: google-github-actions/auth@v2
      with:
        project_id: ecf-bq
        workload_identity_provider: projects/808138694727/locations/global/workloadIdentityPools/early-careers-framework/providers/early-careers-framework

    - name: Apply Terraform
      id: apply-terraform
      shell: bash
      run: |
        make ci ${{ inputs.environment }} terraform-apply
        cd terraform/application && echo "url=$(terraform output -raw url)" >> $GITHUB_OUTPUT
      env:
        TF_VAR_statuscake_api_token: ${{ inputs.statuscake-api-token }}
        DOCKER_IMAGE: ${{ inputs.docker-image }}
        PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}

    - uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - uses: google-github-actions/auth@v2
      with:
        project_id: ecf-bq
        workload_identity_provider: projects/808138694727/locations/global/workloadIdentityPools/early-careers-framework/providers/early-careers-framework

    - name: Seed database
      if: ${{ inputs.pull-request-number != '' }}
      shell: bash
      run: |
        make ci review get-cluster-credentials
        kubectl exec -n cpd-development deployment/cpd-ecf-review-${{ inputs.pull-request-number }}-web -- sh -c "cd /app && /usr/local/bin/bundle exec rails db:safe_reset"
      env:
        PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}


    - uses: ./.github/actions/smoke-test
      with:
        url: ${{ steps.apply-terraform.outputs.url }}
        current-commit-sha: ${{ inputs.current-commit-sha }}
