name: OWasp full scan

inputs:
  target:
    description: The domain name to run the scan against
    required: true
  GITHUB_TOKEN:
    required: true

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: ZAP FULL Scan
      uses: zaproxy/action-full-scan@v0.3.0
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        docker_name: owasp/zap2docker-stable
        target: https://${{ inputs.TARGET }}/sandbox
        rules_file_name: .zap/rules.tsv
        cmd_options: -a
        allow_issue_writing: true

    - uses: actions/download-artifact@v2
      with:
        name: zap_scan
        path: ~/full_scan_report

    - uses: actions/upload-artifact@v2
      with:
        name: full_scan_report
        path: ~/full_scan_report

    - uses: geekyeggo/delete-artifact@v1
      with:
        name: zap_scan
