groups:
  - name: Request-rates
    rules:
      - alert: RequestsFailuresElevated
        # Condition for alerting
        expr: (sum(rate(requests{app="ecf-dev", status_range=~"0xx|4xx|5xx"}[10m]))) / (sum(rate(requests{app="ecf-dev"}[10m])) ) > 0.2
        # Annotation - additional informational labels to store more information
        annotations:
          summary: High rate of failing requests
          description: "ecf-dev: The proportion of failed HTTP requests in the past 5 min is above 10% (current value: {{ humanizePercentage $value }})"
        # Labels - additional labels to be attached to the alert
        labels:
          environment: development
          severity: low

  - name: CPU-usage
    rules:
      - alert: AppCPUHigh
        expr: avg by ( app ) (cpu{app="ecf-dev"}) > 60
        for: 5m
        annotations:
          summary: App CPU usage high
          description: "App CPU usage at least 60% for more than 5 minutes (current value: {{ $value }})"
        labels:
          environment: development
          severity: low
      - alert: WorkerCPUHigh
        expr: avg by ( app ) (cpu{app="ecf-dev-worker"}) > 75
        for: 10m
        annotations:
          summary: Worker CPU usage high
          description: "ecf-dev: Worker CPU usage at least 75% for more than 10 minutes (current value: {{ $value }})"
        labels:
          environment: development
          severity: low

  - name: Disk-utilisation
    rules:
      - alert: DiskUtilisationHigh
        expr: avg by ( app ) ( disk_utilization{ app=~"ecf-dev" }) > 60
        for: 5m
        annotations:
          summary: Disk Utilization High
          description: "ecf-dev: Disk utilization at least 60% for more than 5 minutes (current value: {{ $value }})"
        labels:
          environment: development
          severity: low

  - name: Memory-utilisation
    rules:
      - alert: MemoryUtilizationHigh
        expr: avg by ( app ) (memory_utilization{app=~"ecf-dev"}) > 75
        for: 5m
        annotations:
          summary: Memory Utilization High
          description: "ecf-dev: Memory utilization at least 60% for more than 5 minutes (current value: {{ $value }})"
        labels:
          environment: development
          severity: low

  - name: Crashed-apps
    rules:
      - alert: AppsCrashed
        expr: rate(crash{app=~"ecf-dev"}[1m])*60 > 1
        annotations:
          summary: Crashed Apps non-zero
          description: "ecf-dev: At least 1 crashed app (current value: {{ $value }})"
        labels:
          environment: development
          severity: low
