---
:shared:
  :participant_outcomes:
  - id
  - state
  - completion_date
  - participant_declaration_id
  - created_at
  - updated_at
  - qualified_teachers_api_request_successful
  - sent_to_qualified_teachers_api_at
  :school_cohorts:
  - id
  - induction_programme_choice
  - school_id
  - cohort_id
  - created_at
  - updated_at
  - estimated_teacher_count
  - estimated_mentor_count
  - core_induction_programme_id
  - opt_out_of_updates
  - default_induction_programme_id
  - appropriate_body_id
  :schools:
  - id
  - created_at
  - updated_at
  - urn
  - name
  - school_type_code
  - address_line1
  - address_line2
  - address_line3
  - postcode
  - network_id
  - domains
  - school_type_name
  - ukprn
  - school_phase_type
  - school_phase_name
  - school_website
  - school_status_code
  - school_status_name
  - secondary_contact_email
  - primary_contact_email
  - administrative_district_code
  - administrative_district_name
  - slug
  - section_41_approved
  :partnerships:
  - id
  - created_at
  - updated_at
  - school_id
  - lead_provider_id
  - cohort_id
  - delivery_partner_id
  - challenged_at
  - challenge_reason
  - challenge_deadline
  - pending
  - report_id
  - relationship
  :participant_outcome_api_requests:
  - id
  - request_path
  - status_code
  - request_headers
  - request_body
  - response_body
  - response_headers
  - participant_outcome_id
  - created_at
  - updated_at
  :participant_declarations:
  - id
  - declaration_type
  - declaration_date
  - created_at
  - updated_at
  - user_id
  - course_identifier
  - evidence_held
  - type
  - cpd_lead_provider_id
  - state
  - participant_profile_id
  - superseded_by_id
  - sparsity_uplift
  - pupil_premium_uplift
  - delivery_partner_id
  - mentor_user_id
  - cohort_id
  :npq_applications:
  - id
  - npq_lead_provider_id
  - npq_course_id
  - teacher_reference_number
  - teacher_reference_number_verified
  - school_urn
  - headteacher_status
  - active_alert
  - eligible_for_funding
  - funding_choice
  - lead_provider_approval_status
  - school_ukprn
  - created_at
  - updated_at
  - participant_identity_id
  - works_in_school
  - employer_name
  - employment_role
  - targeted_support_funding_eligibility
  - cohort_id
  - targeted_delivery_funding_eligibility
  - works_in_nursery
  - works_in_childcare
  - kind_of_nursery
  - private_childcare_provider_urn
  - funding_eligiblity_status_code
  - teacher_catchment
  - teacher_catchment_country
  - employment_type
  - teacher_catchment_iso_country_code
  - itt_provider
  - lead_mentor
  - notes
  - primary_establishment
  - number_of_pupils
  - tsf_primary_eligibility
  - tsf_primary_plus_eligibility
  - eligible_for_funding_updated_by_id
  - eligible_for_funding_updated_at
  - funded_place
  :induction_records:
  - id
  - induction_programme_id
  - participant_profile_id
  - schedule_id
  - start_date
  - end_date
  - created_at
  - updated_at
  - training_status
  - preferred_identity_id
  - induction_status
  - mentor_profile_id
  - school_transfer
  - appropriate_body_id
  :appropriate_bodies:
  - id
  - name
  - body_type
  - created_at
  - updated_at
  - disable_from_year
  - listed
  - listed_for_school_type_codes
  :participant_profiles:
  - id
  - school_id
  - type
  - core_induction_programme_id
  - cohort_id
  - mentor_profile_id
  - sparsity_uplift
  - pupil_premium_uplift
  - created_at
  - updated_at
  - status
  - school_cohort_id
  - teacher_profile_id
  - schedule_id
  - npq_course_id
  - school_urn
  - school_ukprn
  - request_for_details_sent_at
  - training_status
  - profile_duplicity
  - participant_identity_id
  - notes
  - induction_start_date
  - induction_completion_date
  - mentor_completion_date
  - mentor_completion_reason
  - cohort_changed_after_payments_frozen
  :cohorts_lead_providers:
  - id
  - lead_provider_id
  - cohort_id
  - created_at
  - updated_at
  :school_local_authority_districts:
  - id
  - school_id
  - local_authority_district_id
  - start_year
  - end_year
  - created_at
  - updated_at
  :school_local_authorities:
  - id
  - school_id
  - local_authority_id
  - start_year
  - end_year
  - created_at
  - updated_at
  :pupil_premiums:
  - id
  - school_id
  - start_year
  - created_at
  - updated_at
  - pupil_premium_incentive
  - sparsity_incentive
  :participant_profile_schedules:
  - id
  - participant_profile_id
  - schedule_id
  - created_at
  - updated_at
  :npq_lead_providers:
  - id
  - name
  - created_at
  - updated_at
  - cpd_lead_provider_id
  - vat_chargeable
  :npq_courses:
  - id
  - name
  - created_at
  - updated_at
  - identifier
  :local_authorities:
  - id
  - created_at
  - updated_at
  - code
  - name
  :lead_providers:
  - id
  - created_at
  - updated_at
  - name
  - cpd_lead_provider_id
  - vat_chargeable
  :cpd_lead_providers:
  - id
  - name
  - created_at
  - updated_at
  :induction_programmes:
  - id
  - school_cohort_id
  - partnership_id
  - core_induction_programme_id
  - training_programme
  - created_at
  - updated_at
  - delivery_partner_to_be_confirmed
  :declaration_states:
  - id
  - participant_declaration_id
  - state
  - created_at
  - updated_at
  - state_reason
  :cohorts:
  - id
  - created_at
  - updated_at
  - payments_frozen_at
  - start_year
  - registration_start_date
  - academic_year_start_date
  - npq_registration_start_date
  - automatic_assignment_period_end_date
  - payments_frozen_at
  :provider_relationships:
  - id
  - lead_provider_id
  - delivery_partner_id
  - cohort_id
  - created_at
  - updated_at
  - discarded_at
  :delivery_partners:
  - id
  - created_at
  - updated_at
  - name
  - discarded_at
  :school_mentors:
  - id
  - participant_profile_id
  - school_id
  - preferred_identity_id
  - created_at
  - updated_at
  - remove_from_school_on
  :induction_coordinator_profiles:
  - id
  - user_id
  - created_at
  - updated_at
  - discarded_at
  - reminder_email_sent_at
  :teacher_profiles:
  - id
  - trn
  - school_id
  - user_id
  - created_at
  - updated_at
  :participant_profile_states:
  - id
  - participant_profile_id
  - state
  - reason
  - created_at
  - updated_at
  - cpd_lead_provider_id
  :participant_id_changes:
  - id
  - user_id
  - from_participant_id
  - to_participant_id
  - created_at
  - updated_at
  :induction_coordinator_profiles_schools:
  - id
  - induction_coordinator_profile_id
  - school_id
  - created_at
  - updated_at
  :nomination_emails:
  - id
  - notify_status
  - sent_to
  - sent_at
  - opened_at
  - school_id
  - created_at
  - updated_at
  - partnership_notification_email_id
  - notify_id
  - delivered_at
  :schedules:
  - id
  - name
  - created_at
  - updated_at
  - schedule_identifier
  - type
  - cohort_id
  - identifier_alias
  :api_requests:
  - id
  - request_path
  - status_code
  - request_headers
  - request_body
  - response_body
  - request_method
  - response_headers
  - cpd_lead_provider_id
  - user_description
  - created_at
  - updated_at
  :support_queries:
  - id
  - user_id
  - zendesk_ticket_id
  - subject
  - created_at
  - updated_at
  :analytics_participants:
  - id
  - user_id
  - user_created_at
  - real_time_attempts
  - real_time_success
  - validation_submitted_at
  - trn_verified
  - school_urn
  - school_name
  - establishment_phase_name
  - participant_type
  - participant_profile_id
  - cohort
  - mentor_id
  - nino_entered
  - manually_validated
  - eligible_for_funding
  - created_at
  - updated_at
  - active
  - training_status
  - sparsity
  - pupil_premium
  - schedule_identifier
  - external_id
  :analytics_appropriate_bodies:
  - id
  - appropriate_body_id
  - name
  - body_type
  - created_at
  - updated_at
  :analytics_schools:
  - id
  - name
  - urn
  - nomination_email_opened_at
  - induction_tutor_nominated
  - tutor_nominated_time
  - induction_tutor_signed_in
  - induction_programme_choice
  - in_partnership
  - partnership_time
  - partnership_challenge_reason
  - partnership_challenge_time
  - lead_provider
  - delivery_partner
  - chosen_cip
  - school_type_name
  - school_phase_type
  - school_phase_name
  - school_status_code
  - school_status_name
  - postcode
  - administrative_district_code
  - administrative_district_name
  - active_participants
  - pupil_premium
  - sparsity
  :statements:
  - id
  - type
  - name
  - cpd_lead_provider_id
  - deadline_date
  - payment_date
  - created_at
  - updated_at
  - cohort_id
  - output_fee
  :statement_line_items:
  - id
  - statement_id
  - participant_declaration_id
  - state
  - created_at
  - updated_at
  :email_associations:
  - id
  - email_id
  - object_type
  - object_id
  - name
  - created_at
  - updated_at
  :emails:
  - id
  - from
  - to
  - template_id
  - template_version
  - uri
  - personalisation
  - created_at
  - updated_at
  - status
  - delivered_at
  - tags
