---
:shared:
  :versions:
  - id
  - item_type
  - event
  - whodunnit
  - object
  - object_changes
  - created_at
  - item_id
  - reason
  :sessions:
  - id
  - session_id
  - data
  - created_at
  - updated_at
  :ecf_duplicates:
  - user_id
  - external_identifier
  - id
  - created_at
  - updated_at
  - primary_participant_profile_id
  - profile_type
  - duplicate_profile_count
  - latest_induction_record_id
  - induction_status
  - training_status
  - start_date
  - end_date
  - school_transfer
  - school_id
  - school_name
  - provider_name
  - training_programme
  - schedule_identifier
  - cohort
  - teacher_profile_trn
  - teacher_profile_id
  - declaration_count
  - participant_profile_status
  :deleted_duplicates:
  - id
  - data
  - primary_participant_profile_id
  - created_at
  - updated_at
  :npq_application_exports:
  - id
  - start_date
  - end_date
  - user_id
  - created_at
  - updated_at
  :npq_application_eligibility_imports:
  - id
  - user_id
  - filename
  - status
  - updated_records
  - import_errors
  - processed_at
  - created_at
  - updated_at
  :statement_line_items:
  - id
  - statement_id
  - participant_declaration_id
  - state
  - created_at
  - updated_at
  :statements:
  - id
  - type
  - name
  - cpd_lead_provider_id
  - deadline_date
  - payment_date
  - created_at
  - updated_at
  - original_value
  - cohort_id
  - output_fee
  - contract_version
  - reconcile_amount
  - marked_as_paid_at
  :schedule_milestones:
  - id
  - name
  - schedule_id
  - milestone_id
  - declaration_type
  - created_at
  - updated_at
  :milestones:
  - id
  - name
  - milestone_date
  - payment_date
  - schedule_id
  - created_at
  - updated_at
  - start_date
  - declaration_type
  :finance_adjustments:
  - id
  - statement_id
  - payment_type
  - amount
  - created_at
  - updated_at
  :data_stage_school_links:
  - id
  - data_stage_school_id
  - link_urn
  - link_type
  - created_at
  - updated_at
  :data_stage_school_changes:
  - id
  - data_stage_school_id
  - attribute_changes
  - status
  - handled
  - created_at
  - updated_at
  :data_stage_schools:
  - id
  - urn
  - name
  - ukprn
  - school_phase_type
  - school_phase_name
  - school_type_code
  - school_type_name
  - school_status_code
  - school_status_name
  - administrative_district_code
  - administrative_district_name
  - address_line1
  - address_line2
  - address_line3
  - postcode
  - primary_contact_email
  - secondary_contact_email
  - school_website
  - created_at
  - updated_at
  - section_41_approved
  - la_code
  :archive_relics:
  - id
  - object_type
  - object_id
  - display_name
  - reason
  - data
  - created_at
  - updated_at
  :sync_dqt_induction_start_date_errors:
  - id
  - participant_profile_id
  - message
  - created_at
  - updated_at
  :support_queries:
  - message
  - additional_information
  :school_links:
  - id
  - school_id
  - link_urn
  - link_type
  - link_reason
  - created_at
  - updated_at
  :schools:
  - la_code
  - la_name
  - establishment_number
  - establishment_status_code
  - establishment_status_name
  - close_date
  - last_changed_date
  - address_1
  - address_2
  - address_3
  - town
  - county
  - easting
  - northing
  - region
  - country
  - establishment_type_code
  - establishment_type_name
  - high_pupil_premium
  - postcode_without_spaces
  - number_of_pupils
  - eyl_funding_eligible
  - phase_type
  - phase_name
  :profile_validation_decisions:
  - id
  - participant_profile_id
  - validation_step
  - approved
  - note
  - created_at
  - updated_at
  :privacy_policy_acceptances:
  - id
  - privacy_policy_id
  - user_id
  - created_at
  - updated_at
  :privacy_policies:
  - id
  - major_version
  - minor_version
  - html
  - created_at
  - updated_at
  :partnership_notification_emails:
  - id
  - token
  - sent_to
  - email_type
  - notify_id
  - notify_status
  - delivered_at
  - partnership_id
  - created_at
  - updated_at
  :partnership_csv_uploads:
  - id
  - lead_provider_id
  - created_at
  - updated_at
  - delivery_partner_id
  - cohort_id
  - uploaded_urns
  :participant_identities:
  - id
  - user_id
  - email
  - external_identifier
  - origin
  - created_at
  - updated_at
  :participant_declaration_attempts:
  - id
  - declaration_type
  - declaration_date
  - user_id
  - course_identifier
  - evidence_held
  - cpd_lead_provider_id
  - participant_declaration_id
  - created_at
  - updated_at
  :participant_bands:
  - id
  - call_off_contract_id
  - min
  - max
  - per_participant
  - created_at
  - updated_at
  - output_payment_percentage
  - service_fee_percentage
  :npq_contracts:
  - id
  - raw
  - version
  - npq_lead_provider_id
  - recruitment_target
  - course_identifier
  - service_fee_installments
  - service_fee_percentage
  - per_participant
  - number_of_payment_periods
  - output_payment_percentage
  - created_at
  - updated_at
  - cohort_id
  - monthly_service_fee
  - targeted_delivery_funding_per_participant
  - special_course
  :npq_applications:
  - date_of_birth
  - nino
  :nomination_emails:
  - token
  :networks:
  - id
  - created_at
  - updated_at
  - name
  - group_type
  - group_type_code
  - group_id
  - group_uid
  - secondary_contact_email
  :local_authority_districts:
  - id
  - created_at
  - updated_at
  - code
  - name
  :lead_provider_profiles:
  - id
  - user_id
  - lead_provider_id
  - created_at
  - updated_at
  - discarded_at
  :lead_provider_cips:
  - id
  - lead_provider_id
  - cohort_id
  - core_induction_programme_id
  - created_at
  - updated_at
  :lead_providers:
  - ecf_id
  - hint
  :finance_profiles:
  - id
  - user_id
  - created_at
  - updated_at
  :feature_selected_objects:
  - id
  - object_type
  - object_id
  - feature_id
  - created_at
  - updated_at
  :features:
  - id
  - name
  - active
  - created_at
  - updated_at
  :event_logs:
  - id
  - owner_type
  - owner_id
  - event
  - data
  - created_at
  - updated_at
  :email_associations:
  - id
  - email_id
  - object_type
  - object_id
  - name
  - created_at
  - updated_at
  :emails:
  - id
  - from
  - to
  - template_id
  - template_version
  - uri
  - personalisation
  - created_at
  - updated_at
  - status
  - delivered_at
  - tags
  :ecf_participant_validation_data:
  - id
  - participant_profile_id
  - full_name
  - date_of_birth
  - trn
  - nino
  - api_failure
  - created_at
  - updated_at
  :ecf_participant_eligibilities:
  - id
  - participant_profile_id
  - qts
  - active_flags
  - previous_participation
  - previous_induction
  - manually_validated
  - status
  - created_at
  - updated_at
  - reason
  - different_trn
  - no_induction
  - exempt_from_induction
  :ecf_ineligible_participants:
  - id
  - trn
  - reason
  - created_at
  - updated_at
  :district_sparsities:
  - id
  - local_authority_district_id
  - start_year
  - end_year
  - created_at
  - updated_at
  :delivery_partner_profiles:
  - id
  - user_id
  - delivery_partner_id
  - created_at
  - updated_at
  :core_induction_programmes:
  - id
  - name
  - created_at
  - updated_at
  :completion_candidates:
  - participant_profile_id
  :call_off_contracts:
  - id
  - version
  - raw
  - uplift_target
  - uplift_amount
  - recruitment_target
  - set_up_fee
  - created_at
  - updated_at
  - lead_provider_id
  - revised_target
  - cohort_id
  - monthly_service_fee
  :appropriate_body_profiles:
  - id
  - user_id
  - appropriate_body_id
  - created_at
  - updated_at
  :api_tokens:
  - id
  - lead_provider_id
  - hashed_token
  - last_used_at
  - created_at
  - updated_at
  - type
  - private_api_access
  - cpd_lead_provider_id
  :api_request_audits:
  - id
  - path
  - body
  - created_at
  - updated_at
  :admin_profiles:
  - id
  - user_id
  - created_at
  - updated_at
  - discarded_at
  - super_user
  :additional_school_emails:
  - id
  - school_id
  - email_address
  - created_at
  - updated_at
  :users:
  - id
  - full_name
  - email
  - login_token
  - login_token_valid_until
  - remember_created_at
  - last_sign_in_at
  - current_sign_in_at
  - current_sign_in_ip
  - last_sign_in_ip
  - sign_in_count
  - created_at
  - updated_at
  - discarded_at
  - get_an_identity_id
  - archived_email
  - archived_at
  - ecf_id
  - trn
  - otp_hash
  - otp_expires_at
  - date_of_birth
  - trn_verified
  - active_alert
  - national_insurance_number
  - trn_auto_verified
  - admin
  - feature_flag_id
  - provider
  - uid
  - raw_tra_provider_data
  - get_an_identity_id_synced_to_ecf
  - super_admin
  - updated_from_tra_at
  - trn_lookup_status
  :courses:
  - id
  - name
  - created_at
  - updated_at
  - ecf_id
  - description
  - position
  - display
  - identifier
  :applications:
  - id
  - user_id
  - course_id
  - lead_provider_id
  - DEPRECATED_school_urn
  - created_at
  - updated_at
  - ecf_id
  - headteacher_status
  - eligible_for_funding
  - funding_choice
  - ukprn
  - teacher_catchment
  - teacher_catchment_country
  - works_in_school
  - employer_name
  - employment_role
  - DEPRECATED_private_childcare_provider_urn
  - works_in_nursery
  - works_in_childcare
  - kind_of_nursery
  - targeted_delivery_funding_eligibility
  - funding_eligiblity_status_code
  - raw_application_data
  - work_setting
  - teacher_catchment_synced_to_ecf
  - employment_type
  - DEPRECATED_itt_provider
  - lead_mentor
  - primary_establishment
  - number_of_pupils
  - tsf_primary_eligibility
  - tsf_primary_plus_eligibility
  - lead_provider_approval_status
  - participant_outcome_state
  - private_childcare_provider_id
  - itt_provider_id
  - school_id
