name: OWasp API scan

inputs:
  target:
    description: The domain name to run the scan against
    required: true
  GITHUB_TOKEN:
    required: true

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: ZAP API Scan
      uses: zaproxy/action-api-scan@v0.1.1
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        docker_name: owasp/zap2docker-stable
        target: https://${{ inputs.TARGET }}/lead-providers/api-docs/v1/api_spec.yml
        format: openapi
        rules_file_name: .zap/rules.tsv
        cmd_options: -a -O ${{ inputs.TARGET }}
        allow_issue_writing: true

    - uses: actions/download-artifact@v2
      with:
        name: zap_scan
        path: ~/api_scan_report

    - uses: actions/upload-artifact@v2
      with:
        name: api_scan_report
        path: ~/api_scan_report

    - uses: geekyeggo/delete-artifact@v1
      with:
        name: zap_scan
