name: Backup DB
description: Backup GOV.UK PaaS DB upload GitHub artefact

inputs:
  environment:
    description: The name of the environment
    required: true
  staging-username:
    description: PAAS staging username
    required: false
    default: ""
  staging-password:
    description: PAAS staging password
    required: false
    default: ""
  sandbox-username:
    description: PAAS sandbox username
    required: false
    default: ""
  sandbox-password:
    description: PAAS sandbox password
    required: false
    default: ""
  production-username:
    description: PAAS production username
    required: false
    default: ""
  production-password:
    description: PAAS production password
    required: false
    default: ""

runs:
  using: composite

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup cf cli (staging)
      if: inputs.environment == 'staging'
      uses: DFE-Digital/github-actions/setup-cf-cli@master
      with:
        CF_USERNAME: ${{ inputs.staging-username }}
        CF_PASSWORD: ${{ inputs.staging-password }}
        CF_SPACE_NAME: early-careers-framework-staging
        INSTALL_CONDUIT: true

    - name: Setup cf cli (sandbox)
      if: inputs.environment == 'sandbox'
      uses: DFE-Digital/github-actions/setup-cf-cli@master
      with:
        CF_USERNAME: ${{ inputs.sandbox-username }}
        CF_PASSWORD: ${{ inputs.sandbox-password }}
        CF_SPACE_NAME: early-careers-framework-sandbox
        INSTALL_CONDUIT: true

    - name: Setup cf cli (production)
      if: inputs.environment == 'production'
      uses: DFE-Digital/github-actions/setup-cf-cli@master
      with:
        CF_USERNAME: ${{ inputs.production-username }}
        CF_PASSWORD: ${{ inputs.production-password }}
        CF_SPACE_NAME: early-careers-framework-prod
        INSTALL_CONDUIT: true

    - name: Setup postgres client
      uses: DFE-Digital/github-actions/install-postgres-client@master

    - name: Backup database
      shell: bash
      run: |
        cf conduit ecf-postgres-${{ inputs.environment }} -- pg_dump -E utf8 --clean --compress=1 --if-exists --no-owner --no-privileges --verbose -f backup-${{ inputs.environment }}.sql.gz

    - name: Upload backup
      uses: actions/upload-artifact@v3
      with:
        name: backup-${{ inputs.environment }}
        path: backup-${{ inputs.environment }}.sql.gz
        retention-days: 1
