# frozen_string_literal: true

# If you do not have OpenSSL installed, change
# the following line to use "http://"
source "https://rubygems.org"

ruby "2.7.4"

# Include the tech docs gem
gem "govuk_tech_docs"

group :test do
  gem "capybara"
  gem "rspec"
end
