# frozen_string_literal: true

# If you do not have OpenSSL installed, change
# the following line to use "http://"
source "https://rubygems.org"

ruby "3.2.2"

# Include the tech docs gem
gem "govuk_tech_docs"

group :development do
  gem "pry"
end

group :test do
  gem "capybara"
  gem "rspec"
end
