name: Backup DB
description: Backup production DB and restore to snapshot DB

inputs:
  environment:
    description: The name of the environment
    required: true
  azure-credentials:
    description: Azure credentials
    required: true

runs:
  using: composite

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}

    - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-credentials: ${{ inputs.azure-credentials }}

    - name: Set AKS credentials
      shell: bash
      run: make ci production get-cluster-credentials

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Install konduit
      shell: bash
      run: make install-konduit

    - name: Backup database schema
      shell: bash
      run: |
        bin/konduit.sh cpd-ecf-${{ inputs.environment }}-web -- pg_dump -E utf8 -C --compress=1 --section=pre-data --clean --if-exists --no-privileges --no-owner --verbose -s -f backup-schema-${{ inputs.environment }}.sql.gz

    - name: Backup database data
      shell: bash
      run: |
        bin/konduit.sh cpd-ecf-${{ inputs.environment }}-web -- pg_dump -E utf8 -Fc --section=data --exclude-table-data api_requests --exclude-table-data versions --compress=1 --no-privileges --no-owner --verbose -a -f backup-data-${{ inputs.environment }}.dump

    - name: Restore snapshot database schema
      shell: bash
      run: bin/konduit.sh -d s189p01-cpdecf-pd-pg-snapshot -k s189p01-cpdecf-pd-app-kv -i backup-schema-${{ inputs.environment }}.sql.gz -c -t 7200 cpd-ecf-${{ inputs.environment }}-web -- psql

    - name: Restore snapshot database data
      shell: bash
      run: bin/konduit.sh -d s189p01-cpdecf-pd-pg-snapshot -k s189p01-cpdecf-pd-app-kv -c -t 7200 cpd-ecf-${{ inputs.environment }}-web -- pg_restore -a -v --no-owner backup-data-${{ inputs.environment }}.dump
