name: Run scheduled database backups
on:
  schedule:
    - cron: "30 4 * * *"
  workflow_dispatch:

jobs:
  backup-and-restore-production:
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Backup
        uses: ./.github/actions/backup-paas-database
        with:
          environment: production
          production-username: ${{ secrets.GOVPAAS_PROD_USERNAME }}
          production-password: ${{ secrets.GOVPAAS_PROD_PASSWORD }}

      - name: Restore
        uses: ./.github/actions/restore-paas-database
        with:
          environment: production
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
