name: Run scheduled database backups
on:
  schedule:
    - cron: "30 4 * * *"

jobs:
  run-backup-and-restore:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, sandbox, production]
    steps:
      - name: Run scheduled backup task for the ${{ matrix.environment }} database
        uses: ./.github/workflows/backup-paas-database.yml
        with:
          environment: ${{ matrix.environment }}
