name: Run scheduled database backups
on:
  schedule:
    - cron: "30 4 * * *"
  workflow_dispatch:

jobs:
  backup-and-restore-staging:
    runs-on: ubuntu-20.04
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Backup
        uses: ./.github/actions/backup-paas-database
        with:
          environment: staging
          staging-username: ${{ secrets.GOVPAAS_STAG_USERNAME }}
          staging-password: ${{ secrets.GOVPAAS_STAG_PASSWORD }}

      - name: Restore
        uses: ./.github/actions/restore-paas-database
        with:
          environment: staging
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

  backup-and-restore-sandbox:
    runs-on: ubuntu-20.04
    environment: sandbox
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Backup
        uses: ./.github/actions/backup-paas-database
        with:
          environment: sandbox
          sandbox-username: ${{ secrets.GOVPAAS_SAND_USERNAME }}
          sandbox-password: ${{ secrets.GOVPAAS_SAND_PASSWORD }}

      - name: Restore
        uses: ./.github/actions/restore-paas-database
        with:
          environment: sandbox
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

  backup-and-restore-production:
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Backup
        uses: ./.github/actions/backup-paas-database
        with:
          environment: production
          production-username: ${{ secrets.GOVPAAS_PROD_USERNAME }}
          production-password: ${{ secrets.GOVPAAS_PROD_PASSWORD }}

      - name: Restore
        uses: ./.github/actions/restore-paas-database
        with:
          environment: production
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
