# This workflow integrates Brakeman with GitHub's Code Scanning feature
# Brakeman is a static analysis security vulnerability scanner for Ruby on Rails applications

name: Brakeman Scan
env:
  BRAKEMAN_VERSION: "7.0.0"

on:
  workflow_call:
    inputs:
      ruby-version:
        description: Ruby version to test against
        type: string
        required: true

jobs:
  brakeman-scan:
    name: Brakeman Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.235.0
        with:
          ruby-version: ${{ inputs.ruby-version }}

      - name: Setup Brakeman
        run: |
          gem install brakeman --version ${{ env.BRAKEMAN_VERSION }}

      - name: Scan
        continue-on-error: true
        run: |
          brakeman -f sarif -o output.sarif.json .

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: output.sarif.json
