name: "Cypress"
on:
  workflow_call:
    inputs:
      run-end-to-end-tests:
        description: Run the e2e Cypress tests
        type: boolean
        required: false
        default: true

jobs:
  e2e-tests:
    if: ${{ inputs.run-end-to-end-tests }}
    name: Run Cypress
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [6]
        ci_node_index: [0, 1, 2, 3, 4, 5]

    env:
      RAILS_ENV: test
      DB_USERNAME: postgres
      DB_PASSWORD: ""
      DB_HOSTNAME: 127.0.0.1
      DB_PORT: 5432
      ANALYTICS_DB_USERNAME: postgres
      ANALYTICS_DB_PASSWORD: ""
      ANALYTICS_DB_HOSTNAME: 127.0.0.1
      ANALYTICS_DB_PORT: 5432
      CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
      CI_NODE_INDEX: ${{ matrix.ci_node_index }}
      CI: true

    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.161.0
        with:
          bundler-cache: true
          ruby-version: "3.2.2"

      - name: Set up Node
        uses: actions/setup-node@v3.8.2
        with:
          node-version: "18.18.x"
          cache: "yarn"

      - name: Install node.js dependencies
        run: yarn install --immutable --refresh-lockfile

      - name: Set up test database
        run: bin/rails db:create db:schema:load

      - name: Prepare assets
        run: bin/rails test:prepare

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          start: bundle exec rails server -e test -p 5017
          wait-on: "http://localhost:5017/"
          command: ${{ github.workspace }}/bin/cypress_ci
