name: Deploy to Dev

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'documentation/**'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: softprops/turnstyle@v1
        name: Check workflow concurrency
        with:
          poll-interval-seconds: 20
          same-branch-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        name: Checkout Code

      - name: Pin Terraform version
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.14.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_DEV_PASSWORD }}

      - name: Build and push docker image from builder target
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: BUILDKIT_INLINE_CACHE=1
          cache-from: |
            dfedigital/early-careers-framework-dev:engage-and-learn-builder
          push: true
          tags: dfedigital/early-careers-framework-dev:engage-and-learn-builder
          target: builder

      - name: Build and push docker image from engage-and-learn-gems-node-modules target
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: BUILDKIT_INLINE_CACHE=1
          cache-from: |
            dfedigital/early-careers-framework-dev:engage-and-learn-gems-node-modules
          push: true
          tags: dfedigital/early-careers-framework-dev:engage-and-learn-gems-node-modules
          target: engage-and-learn-gems-node-modules

      - name: Build and push docker image from assets-precompile target
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: BUILDKIT_INLINE_CACHE=1
          cache-from: |
            dfedigital/early-careers-framework-dev:engage-and-learn-assets-precompile
          push: true
          tags: dfedigital/early-careers-framework-dev:engage-and-learn-assets-precompile
          target: assets-precompile

      - name: Build and push docker image from production target
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            SHA=${{ github.sha }}
          cache-from: |
            dfedigital/early-careers-framework-prod:engage-and-learn-latest
          push: true
          tags: |
            dfedigital/early-careers-framework-prod:engage-and-learn-${{ github.sha }}
            dfedigital/early-careers-framework-prod:engage-and-learn-latest
          target: production

      - name: Deploy to dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_paas_user: ${{ secrets.GOVPAAS_DEV_USERNAME }}
          TF_VAR_paas_password: ${{ secrets.GOVPAAS_DEV_PASSWORD }}
        run: |
          export TF_VAR_paas_app_docker_image=dfedigital/early-careers-framework-prod:engage-and-learn-${{ github.sha }}
          cd terraform/app
          terraform init -reconfigure -input=false -backend-config="bucket=paas-s3-broker-prod-lon-583f04ed-cc98-4c9d-b633-a3a6fa3785b5"
          terraform apply -input=false -auto-approve -var-file ../workspace-variables/dev.tfvars -var='secret_paas_app_env_values={"RAILS_MASTER_KEY":"${{secrets.RAILS_MASTER_KEY_DEV}}"}'
