name: "Manually deploy to an environment"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy environment"
        required: true
        default: migration
        type: choice
        options:
          - review
          - staging
          - migration
          - sandbox
          - production




permissions:
  id-token: write
  pull-requests: write
  packages: write
  security-events: write

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      run: echo "This job is a placeholder for building and pushing the Docker image. It can be replaced with actual build steps."

