name: "Manually deploy to an environment"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy environment"
        required: true
        default: migration
        type: choice
        options:
          - review
          - staging
          - migration
          - sandbox
          - production
      build:
        description: "Build the Docker image"
        required: true
        default: false
        type: boolean
      sha:
        description: Commit sha to be deployed
        required: true

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "This job is a placeholder for building and pushing the Docker image. It can be replaced with actual build steps."

