name: Deploy monitoring stack to Production

on:
  workflow_dispatch:

jobs:
  deploy-monitoring-production:
    name: deploy monitoring stack
    runs-on: ubuntu-20.04
    concurrency:
      group: deploy-monitoring-production
    steps:
      - uses: actions/checkout@v3
        name: Checkout Code

      - name: Pin Terraform version
        uses: hashicorp/setup-terraform@v1.4.0
        with:
          terraform_version: 0.14.0

      - name: Deploy to production
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
          TF_VAR_paas_user: ${{ secrets.GOVPAAS_PROD_USERNAME }}
          TF_VAR_paas_password: ${{ secrets.GOVPAAS_PROD_PASSWORD }}
          TF_VAR_google_client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
          TF_VAR_google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          TF_VAR_grafana_admin_password: ${{ secrets.GRAFANA_ADMIN_PASSWORD_PRODUCTION }}
          TF_VAR_alertmanager_slack_url: ${{ secrets.ALERTMANAGER_SLACK_URL }}
        run: |
          cd terraform/monitoring
          terraform init -reconfigure -input=false -backend-config="bucket=paas-s3-broker-prod-lon-037149fa-bf9a-4577-a066-f627d277d6c4"
          terraform apply -input=false -auto-approve -var-file ../workspace-variables/monitoring/production.tfvars
