name: "Manually deploy to an environment"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        required: true
        default: "review"
      build:
        description: "Build the Docker image"
        required: true
        type: boolean
      sha:
        description: Commit sha to be deployed
        required: true
      pr-number:
        description: "Pull request number"
        required: true
        type: number

permissions:
  id-token: write
  pull-requests: write
  packages: write
  security-events: write

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build == 'true' }}
    outputs:
      docker-image: ${{ steps.build-docker-image.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      - uses: DFE-Digital/github-actions/build-docker-image@master
        id: build-docker-image
        with:
          docker-repository: ghcr.io/dfe-digital/early-careers-framework
          github-token: ${{ secrets.GITHUB_TOKEN }}
          snyk-token: ${{ secrets.SNYK_TOKEN }}


  deploy_review:
    name: Deploy review
    concurrency: deploy_review_${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    environment:
      name: review
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.sha }}

      - name: setup environment variables
        run: |
          if [ ${{ inputs.build }} == 'true' ]
          then
            echo "IMAGE_TAG=$${{ steps.docker.outputs.docker-image }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ inputs.sha }}" >> $GITHUB_ENV
          fi

      - uses: ./.github/actions/deploy-environment-to-aks
        id: deploy
        with:
          docker-image: ${{ env.IMAGE_TAG }}
          environment: ${{ github.event.inputs.environment }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          pull-request-number: ${{ inputs.pr-number }}
          #OVERRIDE CURRENT-COMMIT WITH ANY COMMIT OFF A BRANCH
          current-commit-sha: ${{ inputs.sha }}
          statuscake-api-token: ${{ secrets.STATUSCAKE_API_TOKEN }}
