name: "Manually deploy to an environment"

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: Set branch name
        required: true
        type: string


jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "This job is a placeholder for building and pushing the Docker image. It can be replaced with actual build steps."

