name: "Manually deploy to an environment"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy environment"
        required: true
        default: migration
        type: choice
        options:
          - review
          - staging
          - migration
          - sandbox
          - production
      build:
        description: "Build the Docker image"
        required: true
        default: false
        type: boolean
      sha:
        description: Commit sha to be deployed
        required: true
      pr-number:
        description: PR number for the review app
        required: false
        default: 0


permissions:
  id-token: write
  pull-requests: write
  packages: write
  security-events: write

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
      if ${{ github.event.inputs.build == 'true' }}
    outputs:
      docker-image: ${{ steps.build-docker-image.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      - uses: DFE-Digital/github-actions/build-docker-image@master
        id: build-docker-image
        with:
          docker-repository: ghcr.io/dfe-digital/early-careers-framework
          github-token: ${{ secrets.GITHUB_TOKEN }}
          snyk-token: ${{ secrets.SNYK_TOKEN }}

