name: Deploy to Dev

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'documentation/**'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: setup-inputs
        run: |
          INPUTS='${{ format('{{"environment": "dev", "ref": "{0}"}}', github.sha) }}'
          echo "INPUTS=${INPUTS}" >> $GITHUB_ENV

      - name: trigger-deploy
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Deploy to Environment # Workflow name, in deploy.yml
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: ${{ env.INPUTS }}

      - name: Wait for Deploy App Workflow
        id: wait_for_deploy_app
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          checkName: build docker image and deploy # Job name within workflow
          timeoutSeconds: 900
          intervalSeconds: 15

      - name: Fail if child job fails
        if: ${{ steps.wait_for_deploy_app.outputs.conclusion != 'success' }}
        run: exit 1
