name: Destroy
on:
  pull_request:
    branches: [ develop ]
    types: [ closed ]

jobs:
  destroy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - name: setup-inputs
        run: |
          INPUTS='${{ format('{{"task": "s3:delete_csvs", "env": "{0}"}}', github.event.inputs.environment) }}'
          echo "INPUTS=${INPUTS}" >> $GITHUB_ENV

      - name: Clear S3 bucket
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Run task in dev space # Workflow name
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: ${{ env.INPUTS }}

      - name: Wait for S3 bucket
        id: wait_for_deploy_app
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          checkName: run-task # Job name within workflow
          timeoutSeconds: 600
          intervalSeconds: 15

      - name: Terraform pin version
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 0.14.0

      - name: Destroy review app
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_paas_user: ${{ secrets.GOVPAAS_DEV_USERNAME }}
          TF_VAR_paas_password: ${{ secrets.GOVPAAS_DEV_PASSWORD }}
          TF_VAR_statuscake_username: ${{ secrets.STATUSCAKE_USERNAME }}
          TF_VAR_statuscake_apikey: ${{ secrets.STATUSCAKE_APIKEY }}
        run: |
          cd terraform/app
          terraform init -reconfigure -input=false -backend-config="bucket=paas-s3-broker-prod-lon-7f2ca242-9929-4662-a79c-c454ea56ea7b" -backend-config="key=review-pr-${{ github.event.number }}/terraform.tfstate"
          terraform destroy -input=false -auto-approve -var-file ../workspace-variables/review.tfvars -var='environment=${{github.event.inputs.environment}}'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Delete terraform backend files
        run: |
          aws s3 rm s3://paas-s3-broker-prod-lon-7f2ca242-9929-4662-a79c-c454ea56ea7b/review-pr-${{ github.event.number }}/terraform.tfstate
