name: Generate system diagrams

on:
  push:
    branches: [ 'entity-relationship-diagram-outputs' ]

jobs:
  entity-relationships:
    name: Entity relationships

    runs-on: ubuntu-20.04

    env:
      RAILS_ENV: test
      DB_USERNAME: postgres
      DB_PASSWORD: ''
      DB_HOSTNAME: 127.0.0.1
      DB_PORT: 5432

    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ''
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.70.1
        with:
          bundler-cache: true

      - name: Set up test database
        run: bin/rails db:create db:schema:load

      - name: Create ERD DOT
        run: bundle exec erd --filetype=dot

      - name: Create ERD PDF
        run: bundle exec erd --filetype=pdf

      - name: Publish diagrams
        uses: actions/upload-artifact@v2
        with:
          name: Teacher CPD - entity relationship Diagram
          path: tmp/entity-relationship-diagram.*

  deployment-architecture:
    name: Deployment architecture

    runs-on: ubuntu-20.04

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
      TF_VAR_paas_user: ${{ secrets.GOVPAAS_PROD_USERNAME }}
      TF_VAR_paas_password: ${{ secrets.GOVPAAS_PROD_PASSWORD }}
      TF_VAR_statuscake_username: ${{ secrets.STATUSCAKE_USERNAME }}
      TF_VAR_statuscake_apikey: ${{ secrets.STATUSCAKE_APIKEY }}
      TF_VAR_paas_app_docker_image: dfedigital/early-careers-framework-prod:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Pin Terraform version
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.14.0

      - name: Switch to terraform directory
        run: cd terraform/app

      - name: Run terraform init
        run: terraform init -reconfigure -input=false -backend-config="bucket=paas-s3-broker-prod-lon-7f2ca242-9929-4662-a79c-c454ea56ea7b"

      - name: Run terraform graph
        run: terraform graph -type=validate | dot -Tpng > deployment-architecture.npg

      - name: Publish diagrams
        uses: actions/upload-artifact@v2
        with:
          name: Teacher CPD - deployment architecture
          path: deployment-architecture.*
