name: OWasp Security Scan

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'documentation/**'

# schedule:
#   - cron: '0 12 * * *'

  workflow_dispatch:

env:
  TARGET: s-manage-training-for-early-career-teachers.education.gov.uk

jobs:
  owasp-full:
    name: OWASP Full Scan on Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Post scan started notice on cpd-dev-alerts
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: cpd-dev-alerts
          SLACK_USERNAME: Zap2Docker
          SLACK_ICON: https://avatars.githubusercontent.com/u/6716868?s=100&v=4
          SLACK_TITLE: OWASP Full scan starting!
          SLACK_MESSAGE: Beginning OWasp full scan against https://${{ env.TARGET }}
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.ALERTMANAGER_SLACK_URL }}

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: owasp/zap2docker-stable
          target: https://${{ env.TARGET }}/sandbox
          rules_file_name: .zap/rules.tsv
          cmd_options: -a
          allow_issue_writing: true

      - name: Post scan completed notice on cpd-dev-alerts
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: cpd-dev-alerts
          SLACK_USERNAME: Zap2Docker
          SLACK_ICON: https://avatars.githubusercontent.com/u/6716868?s=100&v=4
          SLACK_TITLE: OWASP Full scan completed!
          SLACK_MESSAGE: OWasp scan completed against https://${{ env.TARGET }}
          SLACK_COLOR: ${{ job.status }}
          MSG_MINIMAL: actions url
          SLACK_WEBHOOK: ${{ secrets.ALERTMANAGER_SLACK_URL }}

      - uses: actions/download-artifact@v2
        with:
          name: zap_scan
          path: ~/full_scan_report

      - uses: actions/upload-artifact@v2
        with:
          name: full_scan_report
          path: ~/full_scan_report

      - uses: geekyeggo/delete-artifact@v1
        with:
          name: zap_scan

  owasp-api:
    name: OWASP API Scan on Staging
    runs-on: ubuntu-latest
    needs: owasp-full

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Post API scan started notice on cpd-dev-alerts
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: cpd-dev-alerts
          SLACK_USERNAME: Zap2Docker
          SLACK_ICON: https://avatars.githubusercontent.com/u/6716868?s=100&v=4
          SLACK_TITLE: OWASP API scan starting!
          SLACK_MESSAGE: Beginning OWasp API scan against https://${{ env.TARGET }}
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.ALERTMANAGER_SLACK_URL }}

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: owasp/zap2docker-stable
          target: https://${{ env.TARGET }}/lead-providers/api-docs/v1/api_spec.yml
          format: openapi
          rules_file_name: .zap/rules.tsv
          cmd_options: -a -O ${{ env.TARGET }}
          allow_issue_writing: true

      - name: Post API scan completed notice on cpd-dev-alerts
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: cpd-dev-alerts
          SLACK_USERNAME: Zap2Docker
          SLACK_ICON: https://avatars.githubusercontent.com/u/6716868?s=100&v=4
          SLACK_TITLE: OWASP API scan completed!
          SLACK_MESSAGE: OWasp API scan completed against https://${{ env.TARGET }}
          SLACK_COLOR: ${{ job.status }}
          MSG_MINIMAL: actions url
          SLACK_WEBHOOK: ${{ secrets.ALERTMANAGER_SLACK_URL }}

      - uses: actions/download-artifact@v2
        with:
          name: zap_scan
          path: ~/api_scan_report

      - uses: actions/upload-artifact@v2
        with:
          name: api_scan_report
          path: ~/api_scan_report

      - uses: geekyeggo/delete-artifact@v1
        with:
          name: zap_scan
