name: "Performance Testing"

on:
  workflow_dispatch:
    inputs:
      scenario:
        description: The performance test scenario to run
        default: smoke-test
      docker-image:
        description: The docker image to run the tests against
        default: ghcr.io/dfe-digital/early-careers-framework:main

jobs:
  test_performance:
    name: "Run performance scenario"
    runs-on: ubuntu-20.04
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run performance scenario
        uses: ./.github/actions/test-performance
        with:
          scenario: ${{ inputs.scenario }}
          docker-image: ${{ inputs.docker-image }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
