name: "Performance Testing"

on:
  workflow_dispatch:
    inputs:
      scenario:
        description: The performance test scenario to run
        default: api-load-test
      docker-image:
        description: The docker image to run the tests against
        default: ghcr.io/dfe-digital/early-careers-framework:main

jobs:
  test_performance:
    name: Run performance tests
    runs-on: ubuntu-latest
    concurrency: test_performance
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ./.github/actions/test-performance
        with:
          scenario: ${{ inputs.scenario }}
          docker-image: ${{ inputs.docker-image }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
