name: Refresh migration DB from production DB
on:
  workflow_dispatch:
    inputs:
      environment:
        description: GitHub environment to refresh from
        type: choice
        default: production
        options:
          - production
        required: true
  # Disable nightly refresh until end to end testing is complete for 2025
  # schedule:
  #   - cron: "0 0 * * *" # Run at midnight.

jobs:
  refresh-migration-db:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Refresh migration DB
        uses: ./.github/actions/refresh-migration-database
        with:
          environment: production
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
        with:
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install kubectl
        uses: DFE-Digital/github-actions/set-kubectl@master

      - name: Set AKS credentials (migration)
        shell: bash
        run: make ci migration get-cluster-credentials

      - name: Generate known keys
        shell: bash
        run: |
          kubectl -n cpd-production exec -ti --tty deployment/cpd-ecf-migration-web -- /bin/sh -c "cd /app && bundle exec rails runner \"PaperTrail.request.whodunnit = %{CI}; Migration::ParityCheck::TokenProvider.new.generate!\""

      - name: Turn off DfE analytics feature flag
        shell: bash
        run: |
          kubectl -n cpd-production exec -ti --tty deployment/cpd-ecf-migration-web -- /bin/sh -c "cd /app && bundle exec rails runner \"FeatureFlag.deactivate(:dfe_analytics)\""
