name: "Refresh Knapsack manifest"

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch: 

jobs:
  refresh_manifest:
    name: Refresh Knapsack manifest
    runs-on: ubuntu-20.04

    env:
      RAILS_ENV: test
      DB_USERNAME: postgres
      DB_PASSWORD: ""
      DB_HOSTNAME: 127.0.0.1
      DB_PORT: 5432

    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-app-env
        id: test
        with:
          prepare-test-database: "true"
          prepare-assets: "true"

      - name: Run tests
        run: KNAPSACK_GENERATE_REPORT=true bundle exec rake knapsack:rspec

      - name: Create pull request 
        uses: peter-evans/create-pull-request@v7
