name: Restore Snapshot DB from production DB
on:
  workflow_dispatch:
    inputs:
      environment:
        description: GitHub environment to backup and restore
        type: choice
        default: production
        options:
          - production
        required: true
      exclude-versions:
        description: Exclude 'versions' table
        type: boolean
      exclude-api-requests:
        description: Exclude 'api_requests' table
        type: boolean

jobs:
  backup-and-restore-production:
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Backup and restore snapshot
        uses: ./.github/actions/backup-and-restore-snapshot-database
        with:
          environment: production
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          exclude-versions: ${{ inputs.exclude-versions }}
          exclude-api-requests: ${{ inputs.exclude-api-requests }}
