name: Trigger release to production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Git tag to deploy
        required: true
jobs:
  create-pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Update production
        run: |
          git fetch --all --tags
          git checkout tags/${{ github.event.inputs.tag }}
          git branch tmp-branch
          git switch production
          git reset --hard tmp-branch --
          git branch -D tmp-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: production-release
          title: Release version ${{ github.event.inputs.version }} to production
          team-reviewers: DFE-Digital/ecf
          base: production

